Document: tpr
Title: Debian tpr Manual
Author: <insert document author here>
Abstract: This manual describes what tpr is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/tpr/tpr.sgml.gz

Format: postscript
Files: /usr/share/doc/tpr/tpr.ps.gz

Format: text
Files: /usr/share/doc/tpr/tpr.text.gz

Format: HTML
Index: /usr/share/doc/tpr/html/index.html
Files: /usr/share/doc/tpr/html/*.html
